title: Minimal theme
logo: /assets/img/ARMTEC Logo Tiny.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-target-blank

# Enable safe mode
safe: true

# Whitelist plugins under safe mode.
# Note that if `some-other-jekyll-plugin` is not listed here it will not be loaded under safe mode.
whitelist:
  - jekyll-target-blank
